services:
  jekyll:
    image: jekyll/jekyll:latest
    command: >
      jekyll serve
      --watch
      --incremental
      --source /srv/jekyll/web
      --config /srv/jekyll/web/_config.yml
    volumes:
      - .:/srv/jekyll
    ports:
      - 4000:4000
